# Generated by Django 4.0.4 on 2023-02-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='imgfolder')),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parlour_Facilitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Parlour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Ph_no', models.IntegerField()),
                ('oping_Time', models.DateTimeField()),
                ('Employee_name', models.ManyToManyField(to='parlour.employee')),
                ('Facilities', models.ManyToManyField(to='parlour.parlour_facilitie')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='expert',
            field=models.ManyToManyField(to='parlour.parlour_facilitie'),
        ),
    ]
