# Generated by Django 4.0.4 on 2023-02-18 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parlour',
            old_name='oping_Time',
            new_name='Oping_Time',
        ),
    ]
