# Generated by Django 4.0.4 on 2023-02-18 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='matrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=30)),
                ('hobbie', models.TextField()),
                ('profession', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=20)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='matrimonial_main_image')),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='matrimonial_image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrimonial_site.matrimonial')),
            ],
        ),
    ]
