# Generated by Django 4.0.4 on 2023-04-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_Appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_address',
            name='closingtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor_address',
            name='opinngtime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
