# Generated by Django 4.0.4 on 2023-02-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('mobileno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('mobileno', models.IntegerField()),
                ('start_location', models.CharField(max_length=100)),
                ('sart_time', models.DateTimeField()),
                ('end_location', models.CharField(max_length=100)),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
