# Generated by Django 3.2 on 2023-03-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='social_image/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='social_video/'),
        ),
    ]
