# Generated by Django 3.2 on 2023-03-18 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialblog', '0002_auto_20230304_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Img',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
