# Generated by Django 3.2 on 2023-03-18 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialblog', '0003_auto_20230318_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img',
            new_name='image',
        ),
    ]
