# Generated by Django 4.0.4 on 2023-02-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=100)),
                ('Author_name', models.CharField(max_length=100)),
                ('Page_number', models.IntegerField()),
                ('description', models.TextField()),
                ('Category', models.CharField(max_length=100)),
                ('Book_Image', models.ImageField(upload_to='mainfloder/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.ManyToManyField(to='Book.createbook')),
            ],
        ),
    ]
