# Generated by Django 4.0.4 on 2023-02-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_createbook_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Name',
        ),
        migrations.AddField(
            model_name='category',
            name='Name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.RemoveField(
            model_name='createbook',
            name='Category',
        ),
        migrations.AddField(
            model_name='createbook',
            name='Category',
            field=models.ManyToManyField(to='Book.category'),
        ),
    ]
