# Generated by Django 3.2 on 2023-02-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_remove_category_name_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createbook',
            name='Book_Image',
            field=models.ImageField(blank=True, null=True, upload_to='mainfloder/'),
        ),
        migrations.AlterField(
            model_name='createbook',
            name='document',
            field=models.FileField(blank=True, default=None, null=True, upload_to='doc/'),
        ),
    ]
