# Generated by Django 3.2 on 2023-04-18 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_auto_20230219_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Category_Image',
            field=models.ImageField(blank=True, null=True, upload_to='mainfloder1/'),
        ),
        migrations.AlterField(
            model_name='createbook',
            name='Author_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='createbook',
            name='Category',
        ),
        migrations.AddField(
            model_name='createbook',
            name='Category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Book.category'),
        ),
        migrations.AlterField(
            model_name='createbook',
            name='Page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='createbook',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
