# Generated by Django 3.2 on 2023-04-08 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ownshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shopname',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ownshop.ownshop'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='ownshop',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ownshop.shopcategory'),
        ),
    ]
