# Generated by Django 3.2 on 2023-04-08 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownshop', '0004_alter_product_product_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownshop',
            old_name='type',
            new_name='type1',
        ),
    ]
