# Generated by Django 3.2 on 2023-04-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownshop', '0005_rename_type_ownshop_type1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownshop',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
