# Generated by Django 3.2 on 2023-04-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownshop', '0006_alter_ownshop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownshop',
            name='img',
            field=models.ImageField(blank=True, default="{% static 'ownshop/img/defaulrshop.jpg' %}", null=True, upload_to='ownshoppic'),
        ),
    ]
