# Generated by Django 3.2 on 2023-04-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownshop', '0007_ownshop_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownshop',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='ownshoppic'),
        ),
    ]
