# Generated by Django 3.2 on 2023-02-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='movieposter/')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
