# Generated by Django 3.2 on 2023-02-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesBazers', '0002_mainmovie_scrollmovie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showmovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('des', models.TextField()),
                ('img', models.ImageField(upload_to='show_movie_poster')),
                ('video', models.FileField(upload_to='movie/')),
            ],
        ),
        migrations.AlterField(
            model_name='mainmovie',
            name='img',
            field=models.ImageField(upload_to='mainmovieposter/'),
        ),
        migrations.AlterField(
            model_name='scrollmovie',
            name='img',
            field=models.ImageField(upload_to='scrollmovieposter/'),
        ),
    ]
